#ifndef _DESIGN_PARAM_H_
#define _DESIGN_PARAM_H_


#define DESIGN_MIN_TIME_KILL_DUCK_TO_COMBO			(1750)
#define DESIGN_COMBO_DUCK_TO_FEVER			(5)
#define DESIGN_FEVER_TIME			(8000)
#define DESIGN_SCARE_DUCK_SPEED_INCREASE			(50)
#define DESIGN_ALL_DUCK_INCREASE_SPEED_AFTER_FEVER			(20)
#define DESIGN_BONUS_TIME_FEVER			(2000)

#endif
